### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by 64J0**
## Description:

With this PR, I'm submitting some code that I think would improve the README of this package.

I'm adding a quote to explain what is Org Babel, and the goal of the project.

I'm also adding an installation example using `straight.el` and `use-package`.

Let me know if you'd like to change something in the PR.

### CODE REVIEW

**Comment by 64J0** [comment]
More information about the use-package configuration: https://github.com/radian-software/straight.el#integration-with-use-package

**Comment by juergenhoetzel** [comment]
> I'm adding a quote to explain what is Org Babel, and the goal of the project.

Thank you :+1: 

> I'm also adding an installation example using `straight.el` and `use-package`.

I guess the use of `straight` to install from `git`  is unnecessary, because the package is also available on melpa: [ob-fsharp](https://melpa.org/#/ob-fsharp)?

**Comment by 64J0** [comment]
> I guess the use of straight to install from git is unnecessary, because the package is also available on melpa: [ob-fsharp](https://melpa.org/#/ob-fsharp)?

You're right, good catch. I'm going to update this part.

**Comment by juergenhoetzel** [comment]
Thank you :+1:

**Pull request merged**
